<a href="https://colab.research.google.com/github/kimchitsigai/Articles-and-Tutorials/blob/master/RL_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import numpy as np

In [0]:
env = gym.make('FrozenLake-v0')


In [3]:
env

<TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>

In [0]:

#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        #le randn est différent pour chacune des 4 actions de l'état courant 
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [6]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4625


In [8]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[3.77394885e-02 7.30126311e-03 5.71924915e-03 7.79516071e-03]
 [1.42329380e-03 3.91167945e-03 1.83398230e-03 1.24025745e-01]
 [1.86820902e-03 1.89634557e-03 2.31937176e-03 1.24892340e-01]
 [1.86001377e-04 2.31961625e-04 8.03343115e-04 4.57683587e-02]
 [3.73928675e-02 8.31728919e-06 5.05993114e-04 1.31298687e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.14062961e-02 4.28088301e-07 1.14659682e-04 1.49686563e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.61327482e-04 2.83958672e-03 4.44349462e-04 2.76391234e-01]
 [3.26603224e-03 6.83586091e-01 7.59889620e-04 1.03917381e-03]
 [5.61996517e-01 8.41273770e-05 5.12516885e-04 5.11116858e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.83166170e-03 7.23136195e-04 8.60379221e-01 6.29525632e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.83976559e-01]
 [0.00000000e+00 0.00000000e+00 0.

In [0]:
#on fait edssous dessous droite etc.